// // <copyright file="TaskKillerLiteSettings.cs" company="PublicDomain.com">
// //     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
// //     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// // </copyright>
// // <auto-generated />
using System;
namespace TaskKillerLite
{
    public class TaskKillerLiteSettings
    {
        public TaskKillerLiteSettings()
        {
        }
    }
}
